name: Docker Image CI
on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Docker meta backend image
        id: meta-back
        uses: docker/metadata-action@v5
        with:
          images: fabianmp/taiga-back
          tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=semver,pattern={{raw}}
      - name: Docker meta frontend image
        id: meta-front
        uses: docker/metadata-action@v5
        with:
          images: fabianmp/taiga-front
          tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=semver,pattern={{raw}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.back
          push: true
          tags: ${{ steps.meta-back.outputs.tags }}
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.front
          push: true
          tags: ${{ steps.meta-front.outputs.tags }}
